<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="01HW198525" name="com.TestSuite.CustomerSearch.MyDesk_CS_005" tests="1" failures="1" timestamp="8 Mar 2017 08:44:39 GMT" time="88.969" errors="0">
  <testcase name="MyDesk_CS_005_Method" time="88.969" classname="com.TestSuite.CustomerSearch.MyDesk_CS_005">
    <failure type="java.lang.AssertionError" message="MyDesk_CS_005_0 script failed, SearchresultCount - MyDesk_CS_005_0.jpg for more details.">
      <![CDATA[java.lang.AssertionError: MyDesk_CS_005_0 script failed, SearchresultCount - MyDesk_CS_005_0.jpg for more details.
	at org.testng.Assert.fail(Assert.java:94)
	at com.Engine.Reporter.exception(Reporter.java:107)
	at com.Engine.Reporter.fnReportFailAndTerminateTest(Reporter.java:91)
	at com.BusinessModules.MyDesk.Home_Page.Verify_SearchResult_Count(Home_Page.java:602)
	at com.TestSuite.CustomerSearch.MyDesk_CS_005.MyDesk_CS_005_Method(MyDesk_CS_005.java:112)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- MyDesk_CS_005_Method -->
</testsuite> <!-- com.TestSuite.CustomerSearch.MyDesk_CS_005 -->
